server:
  port: 8000


spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id: a-service
          uri: http://localhost:8001
          predicates:
            - Path=/a/**
          filters:
            - CustomFilter
        - id: b-service
          uri: http://localhost:8002
          predicates:
            - Path=/b/**