server:
  port: 8000


spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id: a-service
          uri: http://localhost:8001
          predicates:
            - Path=/a/**
          filters:
            - RewritePath=/a/(?<segment>.*), /$\{segment}
            - LoggingFilter
            - CustomFilter
        - id: b-service
          uri: http://localhost:8002
          predicates:
            - Path=/b/**
      default-filters:
        - name: GlobalFilter
          args:
            message: 메세지임
            preLogger: true
            postLogger: true