
insert into member (name) values ('test1')
insert into member (name) values ('test2')

insert into board (member_id, content, title) values (1,'내용내용내용1', '제목제목제목1')
insert into board (member_id, content, title) values (1,'내용내용내용2', '제목제목제목2')
insert into board (member_id, content, title) values (1,'내용내용내용3', '제목제목제목3')
insert into board (member_id, content, title) values (1,'내용내용내용4', '제목제목제목4')
insert into board (member_id, content, title) values (1,'내용내용내용5', '제목제목제목5')
insert into board (member_id, content, title) values (1,'내용내용내용6', '제목제목제목6')
insert into board (member_id, content, title) values (1,'내용내용내용7', '제목제목제목7')

insert into comment (board_id, member_id, content) values (1,1, '댓글1')
insert into comment (board_id, member_id, content) values (1,1, '댓글2')
insert into comment (board_id, member_id, content) values (1,1, '댓글3')
insert into comment (board_id, member_id, content) values (1,1, '댓글4')
insert into comment (board_id, member_id, content) values (1,1, '댓글5')
insert into comment (board_id, member_id, content) values (2,1, '댓글1')
insert into comment (board_id, member_id, content) values (2,1, '댓글2')
insert into comment (board_id, member_id, content) values (2,1, '댓글3')
insert into comment (board_id, member_id, content) values (2,1, '댓글4')
insert into comment (board_id, member_id, content) values (2,1, '댓글5')
insert into comment (board_id, member_id, content) values (3,1, '댓글1')
insert into comment (board_id, member_id, content) values (3,1, '댓글2')
insert into comment (board_id, member_id, content) values (3,1, '댓글3')
insert into comment (board_id, member_id, content) values (3,1, '댓글4')
insert into comment (board_id, member_id, content) values (3,1, '댓글6')
insert into comment (board_id, member_id, content) values (3,1, '댓글7')
insert into comment (board_id, member_id, content) values (3,1, '댓글8')
insert into comment (board_id, member_id, content) values (3,1, '댓글9')
insert into comment (board_id, member_id, content) values (3,1, '댓글10')
insert into comment (board_id, member_id, content) values (3,1, '댓글11')
