server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true # 콘솔창에 SQL 출력
    open-in-view: false # 영속성 컨텍스트의 생존 범위를 트랜잭션 범위로 한정
    properties:
      hibernate:
        format_sql: true # SQL 예쁘게 출력
        default_batch_fetch_size: 1000 # 일대다 컬렉션 조회 시 성능 최적화
    defer-datasource-initialization: true # 데이터 초기화

  messages:
    basename: message/messages
    encoding: UTF-8

  servlet:
    multipart:
      max-file-size: 3MB # 파일 업로드 요청 시 하나의 파일 크기를 10MB 제한
      max-request-size: 3MB # 파일 업로드 요청 시 모든 파일 크기합을 10MB 제한

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100
        size-parameter: pageSize
        one-indexed-parameters: true
