spring:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    properties:
      hibernate:
        #dialect: org.hibernate.dialect.MySQL8Dialect
        default_batch_fetch_size: 1000
        show_sql: true
        format_sql: true
    open-in-view: false
    show-sql: true