# docker-compose.yml
version: "3.8"
services:
  mongo:
    image: mongo
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234
    restart: unless-stopped
    ports:
      - "27017:27017"
    networks:
      - mongodb
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root # mongodb 컨테이너의 root 계정
      - ME_CONFIG_MONGODB_ADMINPASSWORD=1234 # mongodb 컨테이너의 root 비밀번호
      - ME_CONFIG_MONGODB_URL=mongodb://root:1234@mongo:27017/?authSource=admin
      - ME_CONFIG_BASICAUTH_USERNAME=root         # mongo-express 사용자 계정
      - ME_CONFIG_BASICAUTH_PASSWORD=1234         # mongo-express 사용자 비밀번호
    restart: unless-stopped
    ports:
      - "8081:8081"
    networks:
      - mongodb

volumes:
  mongodb-data:

networks:
  mongodb:
    driver: bridge