
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:mem:test'
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-console
#  batch:
#    jdbc:
#      initialize-schema: always
#    job:
#      names: ${job.names:NONE}