spring:
  redis:
    host: localhost
    port: 6379
    password: 1234
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:mem:test'
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: false
        show_sql: true
    defer-datasource-initialization: true
    open-in-view: false
  sql:
    init:
      mode: never



logging:
  level:
    org:
      hibernate:
        engine:
          transaction:
            internal:
              TransactionImpl: debug
#    org.springframework.transaction.interceptor: trace
#    org.springframework.orm.jpa: debug
